In [1]:
# 1. 표준(내장) 라이브러리

# 2. 외장 라이브러리

In [4]:
from random import sample
import math


print(sample(range(1,45+1), k=6))
print(math.pi)
print(math.cos(2*math.pi))

[12, 17, 15, 35, 38, 19]
3.141592653589793
1.0


In [6]:
# 외장 라이브러리는 anaconda가 아닌 이상, 설치 후 사용하셔야 합니다.
# anaconda도 버전 확인을 해야합니다.
# requests
%pip install requests
# %pip install --upgrade requests # 현재 가지고 있는 버전의 업그레이드가 필요할 때 
# %pip install request==2.20.0 # 특정한 버전 설치 필요시


[notice] A new release of pip is available: 23.3.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [7]:
import requests


response = requests.get('https://www.google.com/')
response.status_code

200

## Numpy

In [8]:
%pip install numpy


[notice] A new release of pip is available: 23.3.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [9]:
import numpy as np
# as 앞의 라이브러리를 뒤의 이름으로 부르겠다라는 선언

In [ ]:
# numpy = numerical python의 약자
# ndarray ~= list 
# ndarray: N-dimensional Array, 한가지 자료형만 가질 수 있음
# 핵심기능: Clang > Cpython(Performance)

In [13]:
nums = [10, 20, 30,]
np_array = np.array(nums)
np_array.dtype

dtype('int64')

In [14]:
np.zeros((2,3)) # 영행렬

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
nums = [
    [1,2,3,],
    [4,5,6,]
]
# np.array(nums)
np.ones_like(np.array(nums)) 
np.zeros_like(np.array(nums)) # 기존 어레이 구조에 맞춰 영행렬 생성

array([[0, 0, 0],
       [0, 0, 0]])

In [20]:
np.full((4,3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [21]:
np.full_like(nums, 6) # 기존 어레이 구조에 맞춰 특정 숫자로 행렬을 채움

array([[6, 6, 6],
       [6, 6, 6]])

In [22]:
np.arange(10) # like range(10) 0부터 10개

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
list(range(1,20+1, 4))
np.arange(1,20+1,4) # 시작숫자, 끝숫자-1, 스텝

array([ 1,  5,  9, 13, 17])

In [26]:
np.arange(1,20+1)# 시작숫자, 끝숫자-1 range(1,20+1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [28]:
np.linspace(0, 10, 4) # 0부터 10까지 4개의 숫자를 동간격으로 생성
np.linspace(0, 10, 5) # 0부터 10까지 5개의 숫자를 동간격으로 생성

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [33]:
np.logspace(0,5,6,base=2, dtype=int) # 2^0~ 2^5

array([ 1,  2,  4,  8, 16, 32])

In [34]:
nparray = np.arange(12)

In [35]:
nparray.ndim

1

In [36]:
nparray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
np.ones((2,3)).ndim

2

In [38]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
nparray.shape

(12,)

In [40]:
np.ones((2,3)).shape

(2, 3)

In [41]:
nparray.size

12

In [42]:
np.ones((2,3)).size

6

In [ ]:
# 사진(4000x3000) (0~255,0~255,0~255)= 2^24개의 컬러값 -> np -> 결과물(회색조, 빨간색 제거..)

In [43]:
np.random.normal(0,1,7)

array([ 0.32119772, -0.34109004, -0.16607115,  0.42742388,  0.33909449,
       -0.39505881,  0.61122633])

In [44]:
np.random.normal(0,1,[2,3])

array([[ 1.14037618, -0.70450776, -0.78660429],
       [ 1.28068777,  0.43333439, -0.57843196]])

In [45]:
np.random.randn(8)

array([ 0.06169717,  1.03398922, -0.57806896,  0.3191261 , -0.15192111,
       -1.05414875, -1.21806561, -0.68180275])

In [51]:
np.random.randint(1,45+1, 6)

array([43, 38, 10,  5, 42, 42])

In [56]:
from random import randint


[randint(1,45) for _ in range(6)]

[34, 19, 22, 46, 46, 23]

In [58]:
np.random.seed(2)

In [60]:
np.random.randint(1,45+1, 6)

array([12, 41,  8, 35, 32, 12])

In [ ]:
# random은 random이 아니다!!!!!!!!!
# pseudo random: 의사 랜덤

In [75]:
A = np.random.randint(1,10+1, size=10)
print(A)

[ 1  3  9  9  3 10  7  6  7  7]


In [71]:
A.sort() # 정렬이 바로 적용 됨 python sort

In [72]:
A

array([ 1,  2,  4,  6,  7,  8,  9, 10, 10, 10])

In [77]:
# reverse=True
# np.sort(A) # sorted
A = np.sort(A)[::-1] # python sorted
A

array([10,  9,  9,  7,  7,  7,  6,  3,  3,  1])

In [78]:
B = np.random.randint(1,10, size=[2,3])

In [79]:
B

array([[7, 4, 9],
       [3, 2, 5]])

In [81]:
np.sort(B) # default 행

array([[4, 7, 9],
       [2, 3, 5]])

In [84]:
np.sort(B, axis=0) # 열

array([[3, 2, 5],
       [7, 4, 9]])

In [85]:
np.sort(B, axis=None) # flatten

array([2, 3, 4, 5, 7, 9])

In [89]:
np.sort(np.array([7,2,4]))
np.array([7,2,4]).argsort() # 정렬 후의 상황을 자료의 원본 위치를 이용하여 표현

array([1, 2, 0])

In [100]:
array = np.arange(12)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [101]:
np.reshape(array, (3,4)) # order='C' default

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [102]:
array.reshape(6,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [103]:
np.reshape(array, (3,4), order='F')

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [104]:
array = np.reshape(np.arange(12), (3,4))
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [105]:
array.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [106]:
# Operation

In [107]:
A = np.array([1,2,3])
B = np.array([10,20,30])

In [108]:
A + B

array([11, 22, 33])

In [109]:
A - B

array([ -9, -18, -27])

In [110]:
A * B

array([10, 40, 90])

In [111]:
A / B

array([0.1, 0.1, 0.1])

In [115]:
B > 19

array([False,  True,  True])

In [114]:
A > 2

array([False, False,  True])

In [116]:
B ** 2

array([100, 400, 900])

In [118]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [119]:
B // 7

array([1, 2, 4])

In [120]:
B % 7

array([3, 6, 2])

In [121]:
np.dot(A,B)

140

In [126]:
C = np.array([[1,2,3],[4,5,6]])
D = np.array([[1,2],[3,4],[5,6]])

In [127]:
np.dot(C,D)

array([[22, 28],
       [49, 64]])

In [129]:
E = np.array([[9,4,2],[4,8,5]])

In [130]:
np.min(E)

2

In [131]:
np.max(E)

9

In [132]:
E.min()

2

In [ ]:
E.min()

In [134]:
E.min(axis=1)

array([2, 4])

In [135]:
E.min(axis=0)

array([4, 4, 2])

In [138]:
E

array([[9, 4, 2],
       [4, 8, 5]])

In [137]:
E.sum()

32

In [139]:
np.sum(E)

32

In [141]:
np.sum(E,axis=0)

array([13, 12,  7])

In [142]:
np.sum(E, axis=1)

array([15, 17])

In [143]:
E.cumsum() # -> flatten -> 1-D array에 대한 누적합 실시

array([ 9, 13, 15, 19, 27, 32])

In [144]:
np.cumsum(E)

array([ 9, 13, 15, 19, 27, 32])

In [145]:
np.cumsum(E, axis=0)

array([[ 9,  4,  2],
       [13, 12,  7]])

In [146]:
np.cumsum(E, axis=1)

array([[ 9, 13, 15],
       [ 4, 12, 17]])

In [ ]:
# 평균과 중앙값의 차이
# 평균 mean
# 중앙값 median

In [153]:
A = np.array([
    [8,2,3],
    [4,1,2]
])

In [149]:
A.mean()

3.3333333333333335

In [150]:
np.mean(A)

3.3333333333333335

In [151]:
np.mean(A, axis=1)

array([4.33333333, 2.33333333])

In [152]:
np.mean(A, axis=0)

array([6. , 1.5, 2.5])

In [158]:
np.median(A)

2.5

In [156]:
A.median() # 조심!!! 없음

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [157]:
np.median(A, axis=1)

array([3., 2.])

In [159]:
np.median(A, axis=0)

array([6. , 1.5, 2.5])

In [160]:
np.std(A)

2.285218200133681

In [161]:
np.std(A, axis=1)

array([2.62466929, 1.24721913])

In [162]:
np.std(A, axis=0)

array([2. , 0.5, 0.5])

In [163]:
# Broadcasting
A = np.ones((3,3), dtype=int)
A

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [170]:
value = 10 # [[10,10,10],[10,10,10,],[10,10,10]]

# 만약 broadcasting 이 없었다면 이런식으로 구조를 맞췄어야 하지만..
# np.full()
# [[value for j in range(3)] for i in range(3)]

[[10, 10, 10], [10, 10, 10], [10, 10, 10]]

In [165]:
A+10

array([[11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]])

In [166]:
[[1,2,],[3,4]] + 10

TypeError: can only concatenate list (not "int") to list

In [168]:
word = ['h','e','l','l','o'] # => 'hello'

#1
# result = ''
# for c in word:
#     result += c
# result

#2 fastest
''.join(word)

'hello'

In [173]:
A = np.ones((3,3), dtype=int) # 3x3
A

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [176]:
B = np.array([10,20,30]) # 3x1
B 
# [[10,20,30],[10,20,30],[10,20,30],]

array([10, 20, 30])

In [177]:
A + B

array([[11, 21, 31],
       [11, 21, 31],
       [11, 21, 31]])

In [183]:
C = np.array([[1],[2],[3],[4]]) # 1x4
C

array([[1],
       [2],
       [3],
       [4]])

In [184]:
D = np.array([10,20,30]) # 3x1
D

array([10, 20, 30])

In [185]:
C+D

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33],
       [14, 24, 34]])

In [181]:
B+A

array([[11, 21, 31],
       [11, 21, 31],
       [11, 21, 31]])

In [186]:
D+C

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33],
       [14, 24, 34]])

In [187]:
E = np.ones((2,3))
E

array([[1., 1., 1.],
       [1., 1., 1.]])

In [191]:
F = np.ones((3,2))
F

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [192]:
E+F

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [195]:
A = np.arange(1,15+1).reshape([5,3])
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [197]:
# A[1]
A[1][2]

6

In [199]:
# A[1:3]
A[1:2+1]

array([[4, 5, 6],
       [7, 8, 9]])

In [202]:
A[1:2+1,0:1+1]

array([[4, 5],
       [7, 8]])

In [209]:
nums = list(range(1,15+1))
nums[:4+1]
nums[::3]

[1, 4, 7, 10, 13]

In [210]:
# A[:1+1] # 처음부터
# A[2:] # 끝까지
A[:] # 처음부터 끝까지
A[:, 2] # 처음부터 끝까지 + 2번째 열
A[::2, 2] # 처음부터 끝까지(단, 2칸씩 건너뛰기) + 2번째 열

array([ 3,  9, 15])

In [211]:
# Fancy indexing

In [212]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [214]:
A[[0,1,4]]
A[[4,0,1,]] # 순서파괴 가능

array([[13, 14, 15],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [215]:
A[:, [2,0,1]] # 열에 대한 순서파괴

array([[ 3,  1,  2],
       [ 6,  4,  5],
       [ 9,  7,  8],
       [12, 10, 11],
       [15, 13, 14]])

In [216]:
A[[1:2+1,4]] # 이런건 없어요

SyntaxError: invalid syntax (3828151687.py, line 1)

In [217]:
## Boolean indexing

In [ ]:
# bool -> True False // 0,1 true,false//True,False -> NoneType(none,null)

In [220]:
A = np.arange(1,30+1,3)
A

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [223]:
A # array
A > 13 # 비교연산
A[A > 13] # 13을 초과하는 자료만 남기기

array([16, 19, 22, 25, 28])

## Pandas

In [225]:
%pip install pandas
# 프로젝트 진행중 라이브러리 업데이트는 필요할 때가 아니면 절대 수행하면 안됩니다.
# uv, poetry - package manager
# 최신 라이브러리가 동작할 때 기존의 코드나 다른 라이브러리와의 충분한 검증없이 최신으로 업데이트 할 경우
# 프로젝트가 갑자기 동작하지 않거나, 오류를 뿜뿜할수도 있습니다.
# 모든 팀원이 같은 버전의 라이브러리와 파이썬을 쓰는게 중요합니다.
# 3.3, 3.14(GIL: 멀티코어 대응-> 수많은 라이브러리들이 작업중), 3.10


[notice] A new release of pip is available: 23.3.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [226]:
import pandas as pd

/var/folders/6_/8x9zh_l17v72trp01b9k_kcw0000gn/T/ipykernel_78065/4080736814.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [230]:
df1 = pd.read_csv('./data/customers.csv') # csv 파일 불러오기
df1.head(2) # 동작이 잘 되었는지를 확인할 때 보통 사용하는 메소드(default=5): 앞에서부터 5개

CustomerID                        CustomerName   ContactName  \
0           1                 Alfreds Futterkiste  Maria Anders   
1           2  Ana Trujillo Emparedados y helados  Ana Trujillo   

                         Address         City PostalCode  Country  
0                  Obere Str. 57       Berlin      12209  Germany  
1  Avda. de la Constitución 2222  México D.F.      05021   Mexico

In [231]:
df1.tail() # 마지막 5개 값 보기

CustomerID            CustomerName       ContactName  \
86          87          Wartian Herkku  Pirkko Koskitalo   
87          88  Wellington Importadora     Paula Parente   
88          89    White Clover Markets    Karl Jablonski   
89          90             Wilman Kala   Matti Karttunen   
90          91                  Wolski           Zbyszek   

                        Address      City PostalCode  Country  
86                  Torikatu 38      Oulu      90110  Finland  
87           Rua do Mercado  12   Resende  08737-363   Brazil  
88  305 - 14th Ave. S. Suite 3B   Seattle      98128      USA  
89                Keskuskatu 45  Helsinki      21240  Finland  
90              ul. Filtrowa 68     Walla     01-012   Poland

In [236]:
# pd.read_csv('./data/seongnam-population.csv')
# pd.read_csv('./data/seongnam-population.csv', encoding='utf-8-sig') #1 encoding='utf-8-sig'
df2 = pd.read_csv('./data/seongnam-population.csv', encoding='cp949') #2 encoding='cp949' : MS Office 한글인코딩

In [237]:
df2.head()

구별              동  인구수_계  인구수_남  인구수_여  19세 이상_계  19세 이상_남  19세 이상_여  \
0  수정구  신흥1동           13511   7107   6404     12381      6519      5862   
1  수정구  신흥2동           20239   9911  10328     17042      8328      8714   
2  수정구  신흥3동           11309   5893   5416     10318      5377      4941   
3  수정구  태평1동           15566   7960   7606     14446      7376      7070   
4  수정구  태평2동           15696   7853   7843     13999      6991      7008   

   65세 이상_계  65세 이상_남자  65세 이상_여자   세대수  재외국민  
0      2567       1073       1494  7898     9  
1      2686       1277       1409  7693    22  
2      2020        878       1142  6450     9  
3      3053       1330       1723  8780    23  
4      2774       1156       1618  7976    19

In [239]:
df3 = pd.read_csv('./data/seoul_avg_age.csv')
# 1. 0th row -> 삭제
# 2. 0th col -> 삭제
# 3. 동별(2) -> 구, 구별
# 4. 'value' -> float

In [241]:
df3.index

RangeIndex(start=0, stop=26, step=1)

In [243]:
df3.columns

Index(['동별(1)', '동별(2)', '2019', '2020', '2021', '2022'], dtype='object')

In [246]:
df3.values
df3['2020'][2] + df3['2021'][3] / 2

TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [247]:
df3.head()

동별(1)  동별(2)    2019    2020    2021    2022
0  동별(1)  동별(2)  전체평균연령  전체평균연령  전체평균연령  전체평균연령
1     합계    종로구    44.7    45.2    45.4    45.6
2     합계     중구    45.0    45.6    45.8    46.1
3     합계    용산구    43.9    44.3    44.3    44.4
4     합계    성동구    42.4    43.0    43.4    43.8

In [253]:
# pandas : 어떤 명령을 수행했을 때의 결과물 DataFrame을 보여줌(return)
# 어떤 행동이 내가 갖고있던 DataFrame에 바로 적용되었다고 착각하면 안됨

# df3.drop(0) # 0이라는 index를 가진 행을 지우기
# df3.drop(df3.index[0]) # 0번째 행 지우기
df3.drop(df3.index[0], inplace=True) # inplace=True: 지운 결과물을 확인하고 맘에 든다면, 원본에 적용시키기
df3.head()

동별(1) 동별(2)  2019  2020  2021  2022
1    합계   종로구  44.7  45.2  45.4  45.6
2    합계    중구  45.0  45.6  45.8  46.1
3    합계   용산구  43.9  44.3  44.3  44.4
4    합계   성동구  42.4  43.0  43.4  43.8
5    합계   광진구  41.9  42.4  42.9  43.3

In [256]:
# df3.drop('동별(1)')
# df3.drop('동별(1)', axis=1)
df3.drop('동별(1)', axis=1, inplace=True)
df3.head()

동별(2)  2019  2020  2021  2022
1   종로구  44.7  45.2  45.4  45.6
2    중구  45.0  45.6  45.8  46.1
3   용산구  43.9  44.3  44.3  44.4
4   성동구  42.4  43.0  43.4  43.8
5   광진구  41.9  42.4  42.9  43.3

In [ ]:
df3.head()